package com.example.clientetfgadamboulaiounemuoz.API

class URL {
    companion object {
        const val BASE_URL = "http://10.0.2.2:8080"
        const val REGISTRO = "$BASE_URL/auth/register"
        const val LOGIN = "$BASE_URL/auth/login"
        const val CATEGORIAS = "$BASE_URL/secure/categorias"
        const val CATEGORIAS_CREAR = "$CATEGORIAS"
        const val CATEGORIAS_OBTENER = "$CATEGORIAS"
        const val CATEGORIAS_OBTENER_ID = "$CATEGORIAS/{id}"
        const val CATEGORIAS_ACTUALIZAR = "$CATEGORIAS/{id}"
        const val CATEGORIAS_ELIMINAR = "$CATEGORIAS/{id}"
        const val CHATS = "$BASE_URL/secure/chats"
        const val CHATS_CREAR = "$CHATS"
        const val CHATS_OBTENER = "$CHATS"
        const val CHATS_OBTENER_ID = "$CHATS/{id}"
        const val CHATS_ACTUALIZAR = "$CHATS/{id}"
        const val CHATS_ELIMINAR = "$CHATS/{id}"
        const val CLIENTES = "$BASE_URL/secure/clientes"
        const val CLIENTES_CREAR = "$CLIENTES"
        const val CLIENTES_OBTENER = "$CLIENTES"
        const val CLIENTES_OBTENER_ID = "$CLIENTES/{id}"
        const val CLIENTES_ACTUALIZAR = "$CLIENTES/{id}"
        const val CLIENTES_ELIMINAR = "$CLIENTES/{id}"
        const val DETALLES_PEDIDOS = "$BASE_URL/secure/detalles-pedidos"
        const val DETALLES_PEDIDOS_CREAR = "$DETALLES_PEDIDOS"
        const val DETALLES_PEDIDOS_ELIMINAR = "$DETALLES_PEDIDOS/{id}"
        const val DETALLES_PEDIDOS_ACTUALIZAR = "$DETALLES_PEDIDOS/{id}"
        const val EMPLEADOS = "$BASE_URL/secure/empleados"
        const val EMPLEADOS_CREAR = "$EMPLEADOS"
        const val EMPLEADOS_OBTENER = "$EMPLEADOS"
        const val EMPLEADOS_OBTENER_ID = "$EMPLEADOS/{id}"
        const val EMPLEADOS_ACTUALIZAR = "$EMPLEADOS/{id}"
        const val EMPLEADOS_ELIMINAR = "$EMPLEADOS/{id}"
        const val EMPLEADOS_CHATS = "$BASE_URL/secure/empleados-chats"
        const val EMPLEADOS_CHATS_CREAR = "$EMPLEADOS_CHATS"
        const val EMPLEADOS_CHATS_ELIMINAR = "$EMPLEADOS_CHATS/{id}"
        const val EMPLEADOS_CHATS_ACTUALIZAR = "$EMPLEADOS_CHATS/{id}"
        const val MENSAJES = "$BASE_URL/secure/mensajes"
        const val MENSAJES_CREAR = "$MENSAJES"
        const val MENSAJES_ELIMINAR = "$MENSAJES/{id}"
        const val MENSAJES_ACTUALIZAR = "$MENSAJES/{id}"
        const val MENSAJES_CHAT = "$MENSAJES/chat/{idChat}"
        const val PEDIDOS = "$BASE_URL/secure/pedidos"
        const val PEDIDOS_CREAR = "$PEDIDOS"
        const val PEDIDOS_ELIMINAR = "$PEDIDOS/{id}"
        const val PEDIDOS_ACTUALIZAR = "$PEDIDOS/{id}"
        const val PRODUCTOS = "$BASE_URL/secure/productos"
        const val PRODUCTOS_CREAR = "$PRODUCTOS"
        const val PRODUCTOS_ELIMINAR = "$PRODUCTOS/{id}"
        const val PRODUCTOS_ACTUALIZAR = "$PRODUCTOS/{id}"
        const val VALORACIONES = "$BASE_URL/secure/valoraciones"
        const val VALORACIONES_CREAR = "$VALORACIONES"
        const val VALORACIONES_ELIMINAR = "$VALORACIONES/{id}"
        const val VALORACIONES_ACTUALIZAR = "$VALORACIONES/{id}"
        const val VALORACIONES_PUNTUACION_MEDIA = "$VALORACIONES/puntuacion-media/{idProducto}"
    }
}
